import TextTopStartComputerDeviceBottomCenterShapeHorizontalBottom from "./TextTopStartComputerDeviceBottomCenterShapeHorizontalBottom";

export default TextTopStartComputerDeviceBottomCenterShapeHorizontalBottom;
export { TextTopStartComputerDeviceBottomCenterShapeHorizontalBottom };
export * from "./TextTopStartComputerDeviceBottomCenterShapeHorizontalBottom.types";
