name: CI

on:
  push:
    branches: ["**"] # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build-libs

      - name: Build website
        run: yarn build
        working-directory: apps/website

      - name: check pwd
        run: pwd

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: apps/website/.next
          retention-days: 1

  lighthouse:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: apps/website/.next

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get -y install google-chrome-stable

      - name: Start website
        run: |
          yarn start &
          sleep 5
        working-directory: apps/website

      - name: Run Lighthouse
        run: yarn lhci:mobile
        working-directory: apps/website

      - name: Run Lighthouse (Desktop)
        run: yarn lhci:desktop
        working-directory: apps/website
